### ISSUE TITLE
include a software license

### ISSUE THREAD

**Issue by mekman** [achetverikov/PRESTUS#15]
@achetverikov would you be open to the idea to put PRESTUS under MIT or BSD-3 license to make sure it stays Open Source?

It's of course okay if you prefer not to, but if you do it would be good practise to decide on it early in the development cycle, aka now ;-)

I'd be happy to submit a PR

**Comment by achetverikov** [comment]
Absolutely! Maybe  GNU GPLv3 would be a good choice? To keep it free.
